language: ruby
dist: trusty
sudo: false
rvm:
  - 2.3.1
cache: bundler

addons:
  postgresql: "9.6"

services:
  - postgresql
  - redis

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - /bin/bash travisSetup.sh
  - bundle exec rake